---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  params:
    - name: image-name
      type: string
      default: "nodejshandson"
    - name: registry
      type: string
      default: "docker.io"
  resources:
    - name: git-repo
      type: git
  tasks:
    - name: lint
      taskRef:
        name: npm
      params:
        - name: pathContext
          value: app
        - name: action
          value: run lint
      resources:
        inputs:
          - name: repo
            resource: git-repo
    - name: test
      taskRef:
        name: npm
      params:
        - name: pathContext
          value: app
        - name: action
          value: run test
      resources:
        inputs:
          - name: repo
            resource: git-repo
    - name: build-and-deploy
      params:
        - name: image-name
          value: $(params.image-name)
        - name: registry
          value: $(params.registry)
      taskRef:
        name: s2i-nodejs
      resources:
        inputs:
          - name: repo
            resource: git-repo
      runAfter:
        - lint
        - test