# Here lies all the hardware requirement
# for the virtual box needed to be created
# using vagrantfile that have been defined
ip:
  master1: 192.168.56.25
  master2: 192.168.56.26
  master3: 192.168.56.27
  worker1: 192.168.56.101
  worker2: 192.168.56.102
  monitor: 192.168.56.50
  dbase: 192.168.56.60

mac:
  master1: 0800271333ce
  master2: 582a2ba1af97
  master3: 58fd69a086cd
  worker1: 58fdbb92d6cd
  worker2: 143235bfe733
  monitor: 6c15d491196d
  dbase: 488ba2150148

vagrantBox: "geerlingguy/centos7"
box_version: "7.0"

master:
  count: 3
  cpus: 6
  memory: 2400
  cpuexecutioncap: 100

worker:
  count: 2
  cpus: 6
  memory: 2000
  cpuexecutioncap: 100

monitoring:
  hostname: "monitoring"
  cpus: 1
  memory: 800
  cpuexecutioncap: 50

database:
  hostname: "dbase"
  cpus: 1
  memory: 800
  cpuexecutioncap: 50
