---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-lister
spec:
  params:
    - name: contextDir
      description: "The context directory within the repository for sources"
      default: helloww
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: ls-build-sources
      image: busybox
      command: ["ls", "-ltr", "/workspace/git-source/$(inputs.params.contextDir)"]