---
# Main progress

- name: Verifying installation...
  include_tasks: verify.yaml

- name: Installation...
  include_tasks: install.yaml
  when: not rke2_worker_exist

- name: Verifying installation...
  include_tasks: verify.yaml
  when: not rke2_worker_exist

- name: Making config files...
  include_tasks: config.yaml
  when: rke2_worker_exist