---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello

spec:
  params:
    - name: person
      description: The name we gonna say hello to
      default: World
      type: string
  steps:
    - name: say-hello
      image: alpine
      command:
        - echo
      args:
        - "Hello,.. uhhhh $(params.person)!"