apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1-demo
  namespace: nfs
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
