---
# Main progress

- name: Verifying installation...
  include_tasks: verify.yaml

- name: Installation...
  include_tasks: install.yaml
  when: rke2_exist == False

- name: Verifying installation...
  include_tasks: verify.yaml
  when: rke2_exist == False

- name: Making config files...
  include_tasks: config.yaml
  when: rke2_exist == True